name: flutter_pubnub
description: A cross platform plugin for creating real time messaging applications with PubNub
version: 0.5.0
homepage: https://github.com/Ingenio/flutter_pubnub

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Generate UUID for each PubNub client
  # https://pub.dartlang.org/packages/uuid
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
